# Generated by Django 5.2.12 on 2026-03-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_modelo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cor',
            options={'verbose_name': 'Cor', 'verbose_name_plural': 'Cores'},
        ),
    ]
